version: '3.8' # version del docker-compose(?)
services: 
  nginx: # 1er servicio: nginx
    image: nginx:alpine # imagen de docker hub que vamos a usar
    container_name: nginx # nombre para referirse al servicio
    ports:
      - 8888:80 # puerto de mi pc:puerto del servicio
    volumes:
      - .:/var/www # carpeta local/ vincula a carpeta de nginx
      - ./nginx/conf.d:/etc/nginx/conf.d # archivo local / reflejado en archivo de la imagen
    depends_on: # para correr este servicio debe estar corriendo php y mysql antes
      - php
      - mysql
    networks: # la red que los conecta se llama laravel
      - laravel-network

    #MySQL Service
  mysql: # 2do servicio: base de datos
    image: mysql:5.7.16 # imagen de docker hub
    container_name: mysql # nombre de referencia del servicio
    restart: unless-stopped # si tiene algun problema, reinicialo
    tty: true
    ports:
      - "33070:3306" #cambio puerto antes 3306:3306 puerto local:puerto del servicio
    environment:  # datos de configuracion del entorno
      MYSQL_DATABASE: ${DB_DATABASE} # importante que tengan comillas
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    
      #SERVICE_TAGS: dev
      #SERVICE_NAME: mysql
    volumes:
        - /dbdata:/var/lib/mysql/
        - ./mysql/my.cnf:/etc/mysql/my.cnf # carpeta local:carpeta de config de mysql
    networks:
      - laravel-network

  php: # 3er servicio
    user: 'www-data:www-data'
    build: # este se construira aqui mismo  
      context: . # ruta de referencia ./
      dockerfile: Dockerfile # nombre del archivo de configuracion de la imagen 
    #image: mikediazsv/my-laravel:1.0
    #image: php:8.2.11-fpm
    container_name: php #
    volumes: # carpeta de proyecto local : carpeta del container que da vida a los archivos PHP
      - .:/var/www
      - ./storage:/var/www/storage
    ports:
      - 9000:80 #
    networks:
      - laravel-network # red
    working_dir: /var/www
    depends_on:
      - mysql
 

#Volumenes
volumes:
  dbdata:
    driver: local

#Network
networks: # declaracion de la red
  laravel-network:
  #  driver: bridge